# Perfil ORACLE — use com o listener/serviço Oracle ligado
# Eclipse: Active profiles = oracle
# Terminal: mvnw spring-boot:run -Dspring-boot.run.profiles=oracle

spring.datasource.url=jdbc:oracle:thin:@localhost:1521:ORCL
spring.datasource.username=rm563960
spring.datasource.password=020607
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=NUTRISPACE
