spring.application.name=nutrispace

# Perfil padrão: Oracle FIAP (schema do usuário rm563960)
spring.profiles.active=oracle

server.port=${PORT:8080}

spring.jackson.serialization.write-dates-as-timestamps=false

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

nutrispace.jwt.secret=NutriSpaceFIAP2026SecretKeyComNoMinimo256BitsParaAssinaturaJWT!!
nutrispace.jwt.expiration-ms=86400000

# Swagger / OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# DevTools
spring.devtools.restart.enabled=true
